### ISSUE TITLE
Discussion on Cleaning Up and Organizing Repository Branches

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/DSCI-532_2024_8_DriveDeepDive#22]
Dear Team, 

I’ve opened this issue to address the growing number of branches in our repository, some of which may no longer be in use. In the previous two team projects, I lost many points due to keeping too many branches. 

I think we should review each branch to identify any that are no longer active or needed and decide which branches can be safely deleted.

Doris

**Comment by charlesxch** [comment]
I'll check the branches to see if they are still in use.
