### ISSUE TITLE
Update group name to follow naming convention

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_8_DriveDeepDive#25]
Hello @MDSFusionist @alanpow @chrisgqy @charlesxch 

I'm checking in on everyone's repos and I noticed that your name is slightly different from the convention I suggested. Could you please change `group08` to just `8`, so that your full repo name is `DSCI-532_2024_8_DriveDeepDive`? You can do this in the settings, and then you need to update our local URL (actually I think github will do an automatic redirect for the duration of the project but otherwise you can use `git remote set-url <new)url>

**Comment by charlesxch** [comment]
We changed the repo name accordingly. Thank you Joel.
