### ISSUE TITLE
Doris Background title section. Both cards and the title? To separate it more from the rest of the app

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/DSCI-532_2024_8_DriveDeepDive#51]
Here is the first feed back item we need to fix - as discussed after class on Thursday Doric said she will play around with the colors of our dashboard to see what fits best. We discussed the idea of making it white and more uniform. Lets see what we end up doing!

**Comment by MDSFusionist** [comment]
This task has been completed! And Thanks for @charlesxch reviewing and merging the change into the main branch. Doris
