### ISSUE TITLE
Charles - Break Code into Multiple Files (Q5)

### ISSUE THREAD

**Issue by alanpow** [UBC-MDS/DSCI-532_2024_8_DriveDeepDive#55]
Looks like @charlesxch has broken up our code into multiple files, this is really good so nice work. I can see that our functions for generating our plots and displaying them have been moved moslty out of the app.py. Good stuff!

**Comment by charlesxch** [comment]
I further split code into different files. All layout code is in `components` folder. All callback functions are in `callback.py`. The dictionary and data are in `constants.py`
