### ISSUE TITLE
Regarding the non-time series plots, it took me some time to find out that the values (i.e., number of cars, number of transactions) represent the total values over the selected time frame given the global filters and sliders. Adding clarification in the plot titles, such as 'Total number over years,' may improve clarity.

### ISSUE THREAD

**Issue by MDSFusionist** [UBC-MDS/DSCI-532_2024_8_DriveDeepDive#77]

**Comment by MDSFusionist** [comment]
We agree that this clarification is crucial for understanding the dashboard's visualizations. We are committed to updating the titles to make them consistent and clear in this milestone. Your feedback is greatly appreciated and helps us improve the usability of our dashboard.

**Comment by chrisgqy** [comment]
Changes are made accordingly.
